name: Deploy to GCP

on:
  push:
    branches:
      - main  # Jab bhi main branch pe push hoga, deployment trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 34.150.155.48 >> ~/.ssh/known_hosts

      - name: Deploy to GCP Server
        run: |
          ssh student-02-584409c29cbb@34.150.155.48 << 'EOF'
            cd ~
            
            # Agar repo pehle se hai to update karo, warna clone karo
            if [ ! -d "my_webapp/.git" ]; then
              git clone https://github.com/Hamza844/my_webapp.git
            else
              cd my_webapp
              git reset --hard
              git pull origin main
            fi

            # Docker Compose Run Karo
            cd ~/my_webapp
            docker compose up -d --build
          EOF
##testing