name: Deploy to GCP

on:
  push:
    branches:
      - main  # Jab bhi main branch pe push hoga, deployment trigger hoga

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup SSH Key
      - name: Setup SSH Key
        run: |
          # SSH key setup
          mkdir -p ~/.ssh
          
          # Save the private key from GitHub Secrets
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the server's SSH host to known hosts to avoid host verification prompts
          ssh-keyscan -H 52.201.165.246 >> ~/.ssh/known_hosts

      # Step 3: Deploy to GCP Server (via SSH)
      - name: Deploy to EC2 server
        run: |
          ssh student-02-584409c29cbb@52.201.165.246 << 'EOF'
            # Navigate to home directory
            cd ~

            # Clone the repository or pull the latest changes if already cloned
            if [ ! -d "my_webapp/.git" ]; then
              git clone https://github.com/Hamza844/my_webapp.git
            else
              cd my_webapp
              git reset --hard
              git pull origin main
            fi

            # Run Docker Compose to build and start the containers
            cd ~/my_webapp
            docker compose up -d --build
          EOF
